image: docker:latest

services:
  - docker:dind

variables:
  DOCKERFILE_FLAVOUR: debian
  PHP_BASE_IMAGE_VERSION: fpm
  PHP_IMAGE_NAME: yiiframework/php
  TEST_YII_VERSION: 11b14ea7df25c37ae262ce6b20167fe30a407367

before_script:
  - env
  - apk add --no-cache git curl docker-compose
  - git clone https://github.com/yiisoft/yii2 _host-volumes/yii2
  - git -C _host-volumes/yii2 checkout ${TEST_YII_VERSION}
  - cp .env-dist .env
  - docker info

build:
  environment:
    name: ${DOCKERFILE_FLAVOUR}/php-${PHP_BASE_IMAGE_VERSION}
  script:
    - docker-compose build
    - docker-compose run --rm php-min php -v
    - docker-compose run --rm php-min php /tests/requirements.php
    - docker-compose run --rm php-dev php /tests/requirements.php
    - docker-compose run --rm -w /yii2 php-dev composer install
    - docker-compose run --rm -w /yii2 php-dev php -d error_reporting="E_ALL ^ E_DEPRECATED" vendor/bin/phpunit tests/framework/ --exclude db
